services:
  front_end:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./client/.env
    ports:
      - 3000:3000
    depends_on:
      - back_end
    volumes:
      - ./client:/client
      - client-node-modules:/client/node_modules
    networks:
      - network

  back_end:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: on-failure
    env_file:
      - ./server/.env
    ports:
      - 8080:8080
    depends_on:
      - redis
    volumes:
      - ./server:/server
      - server-node-modules:/server/node_modules
    networks:
      - network
    command: [ "npm", "run", "dev" ]

  redis:
    image: redis/redis-stack:latest
    ports:
      - 6379:6379
    volumes:
      - redis-cache:/data
    networks:
      - network

volumes:
  server-node-modules:
    name: "server-node-modules"
  client-node-modules:
    name: "client-node-modules"
  redis-cache:
    name: "redis-cache"

networks:
  network:
